# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: new_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='new_server.proto',
  package='com.adonmo.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x10new_server.proto\x12\x10\x63om.adonmo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x02\n\x06\x44\x65vice\x12\x32\n\x0bgeoPosition\x18\x01 \x01(\x0b\x32\x1d.com.adonmo.proto.GeoPosition\x12\x14\n\x0c\x63\x61mpaignCode\x18\x02 \x01(\t\x12\x34\n\x0cscreenStatus\x18\x03 \x01(\x0e\x32\x1e.com.adonmo.proto.ScreenStatus\x12\x12\n\nbrightness\x18\x04 \x01(\x04\x12\x13\n\x0bnetworkType\x18\x05 \x01(\t\x12\x30\n\x0c\x63reationTime\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0e\x61ppVersionName\x18\x07 \x01(\t\x12\x16\n\x0e\x61ppVersionCode\x18\x08 \x01(\x04\"\xab\x01\n\x0bGeoPosition\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x0c\n\x04zone\x18\x03 \x01(\t\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\x02\x12\x0f\n\x07\x61zimuth\x18\x05 \x01(\x02\x12\x0c\n\x04time\x18\x06 \x01(\x04\x12\r\n\x05speed\x18\x07 \x01(\x02\x12\x17\n\x0fsatelliteNumber\x18\x08 \x01(\x04\x12\x10\n\x08\x61ltitude\x18\t \x01(\x02*\x1f\n\x0cScreenStatus\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x42\x12\x42\x10\x44\x65viceStateProtob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SCREENSTATUS = _descriptor.EnumDescriptor(
  name='ScreenStatus',
  full_name='com.adonmo.proto.ScreenStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=523,
  serialized_end=554,
)
_sym_db.RegisterEnumDescriptor(_SCREENSTATUS)

ScreenStatus = enum_type_wrapper.EnumTypeWrapper(_SCREENSTATUS)
OFF = 0
ON = 1



_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='com.adonmo.proto.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='geoPosition', full_name='com.adonmo.proto.Device.geoPosition', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='campaignCode', full_name='com.adonmo.proto.Device.campaignCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='screenStatus', full_name='com.adonmo.proto.Device.screenStatus', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brightness', full_name='com.adonmo.proto.Device.brightness', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='networkType', full_name='com.adonmo.proto.Device.networkType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creationTime', full_name='com.adonmo.proto.Device.creationTime', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appVersionName', full_name='com.adonmo.proto.Device.appVersionName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appVersionCode', full_name='com.adonmo.proto.Device.appVersionCode', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=347,
)


_GEOPOSITION = _descriptor.Descriptor(
  name='GeoPosition',
  full_name='com.adonmo.proto.GeoPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='com.adonmo.proto.GeoPosition.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='com.adonmo.proto.GeoPosition.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone', full_name='com.adonmo.proto.GeoPosition.zone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='com.adonmo.proto.GeoPosition.accuracy', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='azimuth', full_name='com.adonmo.proto.GeoPosition.azimuth', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='com.adonmo.proto.GeoPosition.time', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='com.adonmo.proto.GeoPosition.speed', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='satelliteNumber', full_name='com.adonmo.proto.GeoPosition.satelliteNumber', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='com.adonmo.proto.GeoPosition.altitude', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=521,
)

_DEVICE.fields_by_name['geoPosition'].message_type = _GEOPOSITION
_DEVICE.fields_by_name['screenStatus'].enum_type = _SCREENSTATUS
_DEVICE.fields_by_name['creationTime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['GeoPosition'] = _GEOPOSITION
DESCRIPTOR.enum_types_by_name['ScreenStatus'] = _SCREENSTATUS

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'new_server_pb2'
  # @@protoc_insertion_point(class_scope:com.adonmo.proto.Device)
  ))
_sym_db.RegisterMessage(Device)

GeoPosition = _reflection.GeneratedProtocolMessageType('GeoPosition', (_message.Message,), dict(
  DESCRIPTOR = _GEOPOSITION,
  __module__ = 'new_server_pb2'
  # @@protoc_insertion_point(class_scope:com.adonmo.proto.GeoPosition)
  ))
_sym_db.RegisterMessage(GeoPosition)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\020DeviceStateProto'))
# @@protoc_insertion_point(module_scope)
